#!/usr/bin/env python3
"""
Detect ASTime-style activity transition timestamps from 1-FPS frame captions.

Set OPENAI_API_KEY before running. By default this script calls the official
OpenAI Chat Completions endpoint at https://api.openai.com/v1.

Input text format:
    0.0s: caption for this frame
    1.0s: caption for this frame

Default output JSON format matches the VLM comparison sparse prediction files:
    [
      {
        "role": "assistant",
        "content": "(Video Time = 5.0s) Assistant: A person is sitting on a couch reading a book.",
        "time": 5.0,
        "fps": 12.3,
        "cost": 12.2
      }
    ]

Use --output_schema conversation if you need Act-LLaVA-style files with
video_path/frame_fps/conversation.
"""

from __future__ import annotations

import argparse
import ast
import dataclasses
import datetime as _dt
import hashlib
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


PROMPT_VERSION = "astime_caption_transition_gpt_v3"
DEFAULT_MODEL = (
    os.environ.get("OPENAI_MODEL")
    or os.environ.get("GPT_TRANSITION_MODEL")
    or "gpt-4o"
)
DEFAULT_BASE_URL = "https://api.openai.com/v1"
DEFAULT_OUTPUT_DIRNAME = "gpt4o_transition_output_json"


SYSTEM_PROMPT = """You are a strict activity-transition detector for ASTime videos.

You receive a sequence of 1-FPS frame captions generated by a vision-language
model. The captions are noisy and repetitive. Your job is to output only the
timestamps where the visible human activity changes at a semantic level.

Definition of an activity:
- Human state/posture: standing, sitting, lying/reclining, or a clear posture
  transition if that transition is itself the meaningful event.
- Core action/interaction: falling, drinking, eating, reading, writing,
  pouring, washing, picking up an object, reaching elevated objects, operating
  a microwave, putting on a jacket, taking off a jacket, using a phone, using a
  laptop, carrying heavy objects, stomachache, headache, making coffee, or a
  close paraphrase of these actions.
- A posture change is meaningful when it changes standing/sitting/lying, even
  if the object interaction stays the same.

Selection rules:
- Include the first stable human activity after the person appears.
- Include each later transition to a new stable activity.
- Choose the earliest timestamp where the new activity is clearly visible.
- Every returned timestamp must be one of the input frame timestamps.
- Return transitions in chronological order and do not return duplicate
  timestamps.
- Captions around a boundary may be inconsistent. Prefer the first timestamp
  that is supported by nearby captions rather than an isolated hallucination.
- If a new activity unfolds over a few seconds, use the first clear frame of
  the new semantic state/action.
- If a posture-only change is just a short bridge into a new object interaction
  within the next few seconds, merge it into the later interaction instead of
  outputting a separate posture-only transition.
- Do not output no-person/background periods. Do not output the final empty
  room after a person exits.
- Ignore changes in room description, camera view, clothing description,
  object inventory, gender wording, tense, and paraphrases.
- Ignore minor body/head/hand adjustments unless they are the named activity.
- Distinguish object presence from object use. "Holding a phone" is not
  necessarily "using a phone"; "holding a bottle/cup" is not necessarily
  "drinking" unless the surrounding captions support that interaction.
- Ignore a very brief preparatory presence, such as merely standing or walking
  into frame before the first clear sustained activity, unless it is a meaningful
  activity by itself.
- Do not create multiple transitions for the same stable activity segment just
  because the caption wording changes.
- If the same activity disappears for only one or two noisy frames and then
  returns, keep it as one stable segment unless the intervening activity is
  clearly meaningful and supported by neighboring captions.

Return JSON only using this internal transition-decision schema. Do not invent
new captions. The script will reuse the original frame caption at each returned
timestamp when writing the final prediction file.
{
  "transitions": [5.0, 30.0, 46.0],
  "notes": "optional short global note"
}
"""


USER_PROMPT_TEMPLATE = """Video id: {video_id}
Sampling: one caption per second.
Minimum stability preference: {min_stable_seconds:g} seconds. A one-frame
caption can still be used only when the activity is clear and neighboring
captions are compatible.

Only return timestamps for semantic activity transitions. Do not rewrite the
captions; the script will reuse the original caption text at each returned
timestamp.

Frame-caption sequence:
{frame_block}

Detect the semantically meaningful activity transitions and return JSON only."""


TIME_LINE_RE = re.compile(r"^\s*([-+]?\d+(?:\.\d+)?)\s*s\s*:\s*(.*?)\s*$", re.IGNORECASE)
JSON_OBJECT_RE = re.compile(r"\{.*\}", re.DOTALL)
NO_PERSON_RE = re.compile(r"\b(no people|no person|empty room|no one|nobody)\b", re.IGNORECASE)


@dataclasses.dataclass(frozen=True)
class FrameCaption:
    time: float
    caption: str


@dataclasses.dataclass
class GPTResult:
    parsed: dict[str, Any]
    raw_text: str
    source: str
    cache_key: str | None = None
    elapsed_seconds: float = 0.0


def safe_float(value: Any, default: float = 0.0) -> float:
    if isinstance(value, (int, float)):
        return float(value)
    if value is None:
        return default
    match = re.search(r"[-+]?\d+(?:\.\d+)?", str(value))
    if not match:
        return default
    try:
        return float(match.group(0))
    except ValueError:
        return default


def parse_caption_file(path: Path) -> list[FrameCaption]:
    frames: list[FrameCaption] = []
    last_index: int | None = None
    with open(path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.rstrip("\n")
            if not line.strip():
                continue
            match = TIME_LINE_RE.match(line)
            if match:
                frames.append(FrameCaption(time=float(match.group(1)), caption=match.group(2).strip()))
                last_index = len(frames) - 1
                continue
            if last_index is not None:
                previous = frames[last_index]
                appended = f"{previous.caption} {line.strip()}".strip()
                frames[last_index] = FrameCaption(time=previous.time, caption=appended)
    if not frames:
        raise ValueError(f"no timestamped captions were parsed from {path}")
    return sorted(frames, key=lambda item: item.time)


def format_frame_block(frames: list[FrameCaption]) -> str:
    return "\n".join(f"{frame.time:.1f}s: {frame.caption}" for frame in frames)


def build_user_prompt(video_id: str, frames: list[FrameCaption], min_stable_seconds: float) -> str:
    return USER_PROMPT_TEMPLATE.format(
        video_id=video_id,
        min_stable_seconds=min_stable_seconds,
        frame_block=format_frame_block(frames),
    )


def parse_json_response(content: str) -> dict[str, Any]:
    content = content.strip()
    try:
        parsed = json.loads(content)
    except json.JSONDecodeError:
        match = JSON_OBJECT_RE.search(content)
        if not match:
            raise
        parsed = json.loads(match.group(0))
    if isinstance(parsed, list):
        return {"transitions": parsed}
    if not isinstance(parsed, dict):
        raise ValueError(f"GPT response is not a JSON object/list: {type(parsed).__name__}")
    return parsed


def normalize_for_hash(frames: list[FrameCaption]) -> list[dict[str, Any]]:
    return [{"time": round(frame.time, 3), "caption": re.sub(r"\s+", " ", frame.caption).strip()} for frame in frames]


def make_cache_key(
    model: str,
    video_id: str,
    frames: list[FrameCaption],
    min_stable_seconds: float,
) -> str:
    payload = {
        "prompt_version": PROMPT_VERSION,
        "model": model,
        "video_id": video_id,
        "min_stable_seconds": min_stable_seconds,
        "frames": normalize_for_hash(frames),
    }
    raw = json.dumps(payload, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def load_cache(path: Path | None) -> dict[str, dict[str, Any]]:
    if path is None or not path.exists():
        return {}
    cache: dict[str, dict[str, Any]] = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            key = row.get("cache_key")
            if isinstance(key, str):
                cache[key] = row
    return cache


def append_cache(path: Path | None, row: dict[str, Any]) -> None:
    if path is None:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")


def ast_string_value(node: ast.AST | None) -> str | None:
    if node is None:
        return None
    if hasattr(ast, "Constant") and isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.Str):
        return node.s
    return None


def read_python_string_constants(path: Path, names: set[str]) -> dict[str, str]:
    values: dict[str, str] = {}
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except OSError:
        return values
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            targets = [target.id for target in node.targets if isinstance(target, ast.Name)]
            value = ast_string_value(node.value)
            if not targets or value is None:
                continue
            for target in targets:
                if target in names:
                    values[target] = value
        elif isinstance(node, ast.AnnAssign):
            target = node.target
            value = ast_string_value(node.value)
            if isinstance(target, ast.Name) and target.id in names and value is not None:
                values[target.id] = value
    return values


def resolve_api_config(args: argparse.Namespace) -> tuple[str, str]:
    api_key = args.api_key or os.environ.get("OPENAI_API_KEY") or os.environ.get("GPT_API_KEY")
    base_url = args.base_url or os.environ.get("OPENAI_BASE_URL")

    if args.api_config_python_file:
        constants = read_python_string_constants(
            Path(args.api_config_python_file),
            {"OPENAI_API_KEY", "OPENAI_BASE_URL"},
        )
        api_key = api_key or constants.get("OPENAI_API_KEY")
        base_url = base_url or constants.get("OPENAI_BASE_URL")

    if not api_key:
        raise RuntimeError(
            "OpenAI API key is not set. Export OPENAI_API_KEY, pass --api_key, "
            "or pass --api_config_python_file to reuse a local constants file."
        )
    return api_key, (base_url or DEFAULT_BASE_URL).rstrip("/")


class GPTTransitionDetector:
    def __init__(self, args: argparse.Namespace, api_key: str, base_url: str):
        self.args = args
        self.api_key = api_key
        self.base_url = base_url.rstrip("/")
        self.cache_path = Path(args.cache_path) if args.cache_path else None
        self.cache = load_cache(self.cache_path)
        self.cache_hits = 0
        self.api_calls = 0

    def detect(self, video_id: str, frames: list[FrameCaption]) -> GPTResult:
        cache_key = make_cache_key(self.args.model, video_id, frames, self.args.min_stable_seconds)
        cached = self.cache.get(cache_key)
        if cached and isinstance(cached.get("parsed"), dict):
            self.cache_hits += 1
            return GPTResult(
                parsed=cached["parsed"],
                raw_text=str(cached.get("raw_text", "")),
                source="cache",
                cache_key=cache_key,
                elapsed_seconds=safe_float(cached.get("api_elapsed_seconds"), 0.0),
            )

        user_prompt = build_user_prompt(video_id, frames, self.args.min_stable_seconds)
        raw_text, elapsed = self._call_with_retries(user_prompt)
        parsed = parse_json_response(raw_text)
        result = GPTResult(
            parsed=parsed,
            raw_text=raw_text,
            source="gpt",
            cache_key=cache_key,
            elapsed_seconds=elapsed,
        )
        row = {
            "cache_key": cache_key,
            "prompt_version": PROMPT_VERSION,
            "model": self.args.model,
            "video_id": video_id,
            "min_stable_seconds": self.args.min_stable_seconds,
            "parsed": parsed,
            "raw_text": raw_text,
            "api_elapsed_seconds": elapsed,
            "created_at": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        }
        self.cache[cache_key] = row
        append_cache(self.cache_path, row)
        return result

    def _call_with_retries(self, user_prompt: str) -> tuple[str, float]:
        last_error = ""
        for attempt in range(1, self.args.max_retries + 1):
            try:
                return self._post_chat_completion(user_prompt)
            except Exception as exc:  # noqa: BLE001 - batch conversion should retry API hiccups.
                last_error = f"{type(exc).__name__}: {exc}"
                if attempt < self.args.max_retries:
                    time.sleep(self.args.retry_sleep * attempt)
        raise RuntimeError(f"GPT transition detection failed after retries. Last error: {last_error}")

    def _post_chat_completion(self, user_prompt: str) -> tuple[str, float]:
        url = f"{self.base_url}/chat/completions"
        body = {
            "model": self.args.model,
            "temperature": 0,
            "max_tokens": self.args.max_tokens,
            "response_format": {"type": "json_object"},
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        }
        data = json.dumps(body).encode("utf-8")
        request = urllib.request.Request(
            url,
            data=data,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        self.api_calls += 1
        start = time.time()
        try:
            with urllib.request.urlopen(request, timeout=self.args.timeout) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            message = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"OpenAI HTTP {exc.code}: {message}") from exc
        elapsed = time.time() - start
        return str(payload["choices"][0]["message"]["content"]), elapsed


def output_stem_for_input(input_path: Path, strip_suffixes: list[str]) -> str:
    stem = input_path.stem
    for suffix in strip_suffixes:
        if suffix and stem.endswith(suffix):
            return stem[: -len(suffix)]
    return stem


def infer_video_id(input_path: Path, strip_suffixes: list[str]) -> str:
    return output_stem_for_input(input_path, strip_suffixes)


def format_video_time(time_value: float) -> str:
    text = f"{time_value:.3f}".rstrip("0").rstrip(".")
    if "." not in text:
        text = f"{text}.0"
    return text


def clean_output_caption(caption: str) -> str:
    caption = caption.strip()
    caption = re.sub(r"^\(Video Time\s*=\s*[-+]?\d+(?:\.\d+)?s\)\s*", "", caption)
    caption = re.sub(r"^Assistant:\s*", "", caption)
    caption = re.sub(r"\s+", " ", caption).strip()
    return caption


def build_caption_lookup(frames: list[FrameCaption]) -> dict[float, str]:
    lookup: dict[float, str] = {}
    for frame in frames:
        lookup[round(frame.time, 3)] = clean_output_caption(frame.caption)
    return lookup


def caption_for_time(
    frames: list[FrameCaption],
    time_value: float,
    lookup: dict[float, str] | None = None,
) -> str | None:
    if lookup is None:
        lookup = build_caption_lookup(frames)
    key = round(time_value, 3)
    if key in lookup:
        return lookup[key]
    if not frames:
        return None
    nearest = min(frames, key=lambda frame: abs(frame.time - time_value))
    if abs(nearest.time - time_value) <= 0.51:
        return clean_output_caption(nearest.caption)
    return None


def prediction_from_transition(
    item: Any,
    frames: list[FrameCaption],
    caption_lookup: dict[float, str],
    fps_value: float,
    cost_value: float,
) -> dict[str, Any] | None:
    if isinstance(item, dict):
        time_value = safe_float(item.get("time", item.get("timestamp")), default=-1.0)
    else:
        time_value = safe_float(item, default=-1.0)
    if time_value < 0:
        return None
    caption = caption_for_time(frames, time_value, lookup=caption_lookup)
    if not caption:
        return None
    if NO_PERSON_RE.search(caption):
        return None
    video_time = format_video_time(time_value)
    return {
        "role": "assistant",
        "content": f"(Video Time = {video_time}s) Assistant: {caption}",
        "time": round(time_value, 3),
        "fps": fps_value,
        "cost": cost_value,
    }


def extract_prediction_items(
    parsed: dict[str, Any],
    frames: list[FrameCaption],
    fps_value: float,
    cost_value: float,
) -> list[dict[str, Any]]:
    transitions = parsed.get("transitions", [])
    if not isinstance(transitions, list):
        raise ValueError("GPT JSON must contain a list field named 'transitions'")

    predictions: list[dict[str, Any]] = []
    seen: set[tuple[float, str]] = set()
    caption_lookup = build_caption_lookup(frames)
    for item in transitions:
        prediction = prediction_from_transition(
            item,
            frames=frames,
            caption_lookup=caption_lookup,
            fps_value=fps_value,
            cost_value=cost_value,
        )
        if prediction is None:
            continue
        normalized_caption = re.sub(r"\s+", " ", prediction["content"].lower()).strip()
        key = (float(prediction["time"]), normalized_caption)
        if key in seen:
            continue
        seen.add(key)
        predictions.append(prediction)
    return sorted(predictions, key=lambda row: float(row["time"]))


def render_video_path(video_id: str, args: argparse.Namespace) -> str:
    template = args.video_path_template
    if template:
        return template.format(video_id=video_id)
    return f"dataset/ASTime/videos/test/{video_id}.MP4"


def build_output_payload(
    predictions: list[dict[str, Any]],
    video_id: str,
    args: argparse.Namespace,
) -> Any:
    if args.output_schema == "assistant_list":
        return predictions
    return {
        "video_path": render_video_path(video_id, args),
        "frame_fps": args.frame_fps,
        "conversation": predictions,
    }


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=4, ensure_ascii=False)


def resolve_output_path(input_path: Path, args: argparse.Namespace) -> Path:
    strip_suffixes = args.strip_input_suffix or []
    if args.output_file:
        return Path(args.output_file)
    if args.output_dir:
        return Path(args.output_dir) / f"{output_stem_for_input(input_path, strip_suffixes)}.json"
    if args.input_dir:
        output_dir = Path("output") / DEFAULT_OUTPUT_DIRNAME
        return output_dir / f"{output_stem_for_input(input_path, strip_suffixes)}.json"
    output_dir = Path("output") / DEFAULT_OUTPUT_DIRNAME
    return output_dir / f"{output_stem_for_input(input_path, strip_suffixes)}.json"


def resolve_metadata_path(output_path: Path, args: argparse.Namespace) -> Path | None:
    if not args.metadata_dir:
        return None
    return Path(args.metadata_dir) / f"{output_path.stem}.meta.json"


def process_one_file(
    input_path: Path,
    output_path: Path,
    detector: GPTTransitionDetector | None,
    args: argparse.Namespace,
) -> None:
    frames = parse_caption_file(input_path)
    video_id = infer_video_id(input_path, args.strip_input_suffix or [])
    prompt = build_user_prompt(video_id, frames, args.min_stable_seconds)

    if args.print_prompt:
        print("===== SYSTEM PROMPT =====")
        print(SYSTEM_PROMPT)
        print("===== USER PROMPT =====")
        print(prompt)
        return

    if args.dry_run:
        print(
            f"[dry-run] {input_path} -> {output_path} | "
            f"frames={len(frames)} span={frames[0].time:.1f}-{frames[-1].time:.1f}s "
            f"prompt_chars={len(prompt)} output_schema={args.output_schema}",
            flush=True,
        )
        return

    if output_path.exists() and not args.overwrite:
        print(f"[skip] exists: {output_path}", flush=True)
        return
    if detector is None:
        raise RuntimeError("detector is required unless --dry_run or --print_prompt is used")

    result = detector.detect(video_id, frames)
    output_cost = args.cost_value if args.cost_value is not None else round(result.elapsed_seconds, 6)
    if args.fps_value is not None:
        output_fps = args.fps_value
    elif result.elapsed_seconds > 0:
        output_fps = round(len(frames) / result.elapsed_seconds, 6)
    else:
        output_fps = 0.0
    predictions = extract_prediction_items(
        result.parsed,
        frames=frames,
        fps_value=output_fps,
        cost_value=output_cost,
    )
    output_payload = build_output_payload(predictions, video_id, args)
    write_json(output_path, output_payload)

    metadata_path = resolve_metadata_path(output_path, args)
    if metadata_path is not None:
        metadata = {
            "input_file": str(input_path),
            "output_file": str(output_path),
            "video_id": video_id,
            "prompt_version": PROMPT_VERSION,
            "model": args.model,
            "source": result.source,
            "cache_key": result.cache_key,
            "api_elapsed_seconds": result.elapsed_seconds,
            "output_schema": args.output_schema,
            "output_fps": output_fps,
            "output_cost": output_cost,
            "num_frames": len(frames),
            "num_predictions": len(predictions),
            "raw_gpt_json": result.parsed,
            "raw_gpt_text": result.raw_text,
            "created_at": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        }
        write_json(metadata_path, metadata)

    print(
        f"[ok] {input_path.name}: frames={len(frames)} transitions={len(predictions)} "
        f"source={result.source} -> {output_path}",
        flush=True,
    )


def gather_input_files(args: argparse.Namespace) -> list[Path]:
    if args.input_file and args.input_dir:
        raise SystemExit("Use either --input_file or --input_dir, not both.")
    if not args.input_file and not args.input_dir:
        raise SystemExit("Either --input_file or --input_dir is required.")
    if args.input_file:
        path = Path(args.input_file)
        if not path.exists():
            raise FileNotFoundError(path)
        return [path]
    input_dir = Path(args.input_dir)
    if not input_dir.exists():
        raise FileNotFoundError(input_dir)
    files = sorted(input_dir.glob(args.glob))
    if args.limit_files is not None:
        files = files[: args.limit_files]
    if not files:
        raise FileNotFoundError(f"no files matching {args.glob!r} under {input_dir}")
    return files


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Use GPT-4o to convert frame-wise captions into sparse ASTime transition JSON files."
    )
    parser.add_argument("--input_file", default=None, help="One caption txt file to process.")
    parser.add_argument("--input_dir", default=None, help="Folder containing caption txt files.")
    parser.add_argument("--glob", default="*.txt", help="Glob used with --input_dir.")
    parser.add_argument("--limit_files", type=int, default=None, help="Process only the first N files.")
    parser.add_argument("--output_file", default=None, help="Output JSON path for --input_file.")
    parser.add_argument(
        "--output_dir",
        default=None,
        help=(
            "Output folder for JSON files. Defaults to "
            f"output/{DEFAULT_OUTPUT_DIRNAME} when --output_file is not set."
        ),
    )
    parser.add_argument("--metadata_dir", default=None, help="Optional folder for raw GPT metadata JSON files.")
    parser.add_argument(
        "--output_schema",
        choices=["conversation", "assistant_list"],
        default="assistant_list",
        help="assistant_list matches VLM_select sparse prediction files; conversation matches Act-LLaVA result files.",
    )
    parser.add_argument(
        "--video_path_template",
        default="dataset/ASTime/videos/test/{video_id}.MP4",
        help="Used only for --output_schema conversation. Supports {video_id}.",
    )
    parser.add_argument("--frame_fps", type=float, default=1.0, help="Top-level frame_fps for conversation output.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing output JSON files.")
    parser.add_argument(
        "--strip_input_suffix",
        action="append",
        default=["_result"],
        help="Strip this suffix from input stems when naming output files. Can be repeated.",
    )
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--api_key", default=None, help="OpenAI API key. Prefer OPENAI_API_KEY env.")
    parser.add_argument(
        "--base_url",
        default=None,
        help=f"OpenAI API base URL. Defaults to the official endpoint: {DEFAULT_BASE_URL}",
    )
    parser.add_argument(
        "--api_config_python_file",
        default=None,
        help=(
            "Optional Python file containing OPENAI_API_KEY/OPENAI_BASE_URL string constants. "
            "The file is parsed with ast and is not executed."
        ),
    )
    parser.add_argument("--cache_path", default=None, help="Optional JSONL cache for GPT transition responses.")
    parser.add_argument("--min_stable_seconds", type=float, default=2.0)
    parser.add_argument(
        "--fps_value",
        type=float,
        default=None,
        help="Value written to assistant fps. Defaults to num_input_frames / GPT_elapsed_seconds.",
    )
    parser.add_argument(
        "--cost_value",
        type=float,
        default=None,
        help="Value written to assistant cost. Defaults to GPT API elapsed seconds.",
    )
    parser.add_argument("--max_retries", type=int, default=3)
    parser.add_argument("--retry_sleep", type=float, default=2.0)
    parser.add_argument("--timeout", type=float, default=120.0)
    parser.add_argument("--max_tokens", type=int, default=4096)
    parser.add_argument("--dry_run", action="store_true", help="Parse inputs and show planned outputs without GPT calls.")
    parser.add_argument("--print_prompt", action="store_true", help="Print the prompt for the first input and exit.")
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    input_files = gather_input_files(args)

    detector: GPTTransitionDetector | None = None
    if not args.dry_run and not args.print_prompt:
        api_key, base_url = resolve_api_config(args)
        detector = GPTTransitionDetector(args, api_key=api_key, base_url=base_url)
        print(
            f"model={args.model} base_url={base_url} files={len(input_files)} "
            f"cache={detector.cache_path}",
            flush=True,
        )

    for index, input_path in enumerate(input_files, start=1):
        output_path = resolve_output_path(input_path, args)
        if len(input_files) > 1 and not args.dry_run and not args.print_prompt:
            print(f"[{index}/{len(input_files)}] processing {input_path}", flush=True)
        process_one_file(input_path, output_path, detector, args)
        if args.print_prompt:
            break

    if detector is not None:
        print(f"done | GPT_calls={detector.api_calls} cache_hits={detector.cache_hits}", flush=True)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Interrupted.", file=sys.stderr)
        raise
